Traceback (most recent call last):
  File "run.py", line 3, in <module>
    from app import app
  File "/Users/rachel/mine/personal_projects/pyladiespdx-books/app/__init__.py", line 5, in <module>
    app.config.from_object('config')
  File "/Users/rachel/mine/personal_projects/pyladiespdx-books/venv/lib/python2.7/site-packages/flask/config.py", line 162, in from_object
    obj = import_string(obj)
  File "/Users/rachel/mine/personal_projects/pyladiespdx-books/venv/lib/python2.7/site-packages/werkzeug/utils.py", line 426, in import_string
    sys.exc_info()[2])
  File "/Users/rachel/mine/personal_projects/pyladiespdx-books/venv/lib/python2.7/site-packages/werkzeug/utils.py", line 408, in import_string
    return __import__(import_name)
werkzeug.utils.ImportStringError: import_string() failed for 'config'. Possible reasons are:

- missing __init__.py in a package;
- package or module path not included in sys.path;
- duplicated package or module name taking precedence in sys.path;
- missing module, class, function or variable;

Debugged import:

- 'config' not found.

Original exception:

ImportError: No module named config
